export const DICT_KAA: Record<string, string> = {
  "Kirish": "Кириў", "Boshlash →": "Баслаў →", "Ro'yxatdan o'tish": "Дизимнен өтиў", "Jarayon": "Процесс",
  "Skill Passport": "Кәсиплик паспорт", "Ekotizim": "Экосистема", "FAQ": "Сорақлар", "Til": "Тил",
  "Yorug' rejim": "Жарық тема", "Tun rejimi": "Қараңғы тема", "Bildirishnomalar": "Хабарламалар",
  "Hozircha bildirishnoma yo'q": "Ҳәзирше хабарлама жоқ", "Hammasini o'qildi deb belgilash": "Ҳәммесин оқылған деп белгилеў",
  "Chiqish": "Шығыў", "Menyu": "Меню", "Passport": "Паспорт", "Yopish": "Жабыў", "Bekor qilish": "Бийкар етиў",
  "Saqlash": "Сақлаў", "Tahrirlash": "Өзгертиў", "Tasdiqlash": "Тастыйықлаў", "Rad etish": "Қабыл етпеў", "Barchasi": "Ҳәммеси",
  "Shahar": "Қала", "Tozalash": "Тазалаў", "Izoh": "Иzah", "Sana": "Сәне", "Vaqt": "Ўақыт", "Turi": "Түри",
  "Kandidat": "Кандидат", "Tanlang...": "Таңлаң...", "Yuborish": "Жибериў", "Baholash": "Баҳалаў", "Jami": "Жәми",
  "Video": "Видео", "Ofisda": "Офисте", "Telefon": "Телефон", "kun": "күн", "ariza": "арза", "navbatda": "гезекте",
  "baho": "баҳа", "readiness": "тайынлық", "savol": "сорақ", "daqiqa": "мин", "o'rin": "орын", "Namuna savol": "Үлги сорақ",
  "tez kunda": "жақында", "Yuqori tayyor": "Жоқары тайын", "Ishga tayyor": "Жумысқа тайын", "Rivojlanmoqda": "Раўажланбақта", "Boshlang'ich": "Басланғыш",
  "Talaba paneli": "Студент панелі", "Employer paneli": "Жумыс бериўши панелі", "Mentor paneli": "Ментор панелі",
  "Universitet paneli": "Университет панелі", "Admin panel": "Админ панелі",
  "Dashboard": "Басқарыў панели", "Assessmentlar": "Баҳалаўлар", "Practice tasks": "Практика", "Loyihalar": "Проектлер",
  "Arizalarim": "Арзаларым", "Interviewlar": "Сәўбетлер", "Offerlar": "Усыныслар", "AI Dashboard": "AI панель",
  "Kandidatlar": "Кандидатлар", "Blind Review": "Соқыр шолыў", "Tasklar": "Ўазыйпалар", "Tekshirish navbati": "Тексериў гезеги",
  "Feedbacklar": "Пикирлер", "Talabalar": "Студентлер", "Analytics": "Аналитика", "Foydalanuvchilar": "Пайдаланыўшылар",
  "Skill katalogi": "Кәсип каталогы", "Audit log": "Аудит журналы",
  "PILOT · TATU × 10 KOMPANIYA": "ПИЛОТ · TATU × 10 КОМПАНИЯ", "1 kasb: Junior Frontend Developer": "1 кәсип: Junior Frontend Developer",
  "Diplom yetarli emas.": "Диплом жеткиликли емес.", "Tajribani isbotlang.": "Тәжирийбени дәлиллең.",
  "hero_sub": "KASBORA студентлерди ҳақыйқый проектлер, тастыйықланған кәсиплер ҳәм жумыс бериўшилер менен байланыстырып, университеттен жумысқа шекемги жолды қысқартады. Резюмедеги ўәде емес — дәлилленген тәжирийбе.",
  "Talaba sifatida boshlash": "Студент сыпатында баслаў", "aud_st_d": "Баҳалаў · проект · паспорт",
  "Ish beruvchi sifatida qo'shilish": "Жумыс бериўши сыпатында қосылыў", "aud_em_d": "Тастыйықланған талантлар · проектлер · жумысқа алыў",
  "Universitet sifatida hamkorlik": "Университет сыпатында бирге ислесиў", "aud_un_d": "Студентлер тайынлығын реал ўақытта бақлаў",
  "1 universitet · pilot": "1 университет · пилот", "10 kompaniya · real loyihalar": "10 компания · ҳақыйқый проектлер", "100+ talaba · birinchi oqim": "100+ студент · биринши ағым",
  "Talaba yo'li — jonli simulyatsiya": "Студент жолы — жаны симуляция",
  "O'rganish": "Үйрениў", "Isbotlash": "Дәлиллеў", "Amaliyot": "Практика", "Real loyiha": "Ҳақыйқый проект", "Pasport": "Паспорт",
  "Ish beruvchi": "Жумыс бериўши", "Suhbat": "Сәўбет", "Task": "Ўазыйпа", "Ishga joylashish": "Жумысқа орналасыў",
  "OFFER QABUL QILINDI → HIRED": "УСЫНЫС ҚАБЫЛ ЕТИЛДИ → ЖУМЫСҚА АЛЫНДЫ",
  "Pilotda ishtirok etayotganlar": "Пилот қатнасыўшылары", "10 kompaniya · 1 universitet": "10 компания · 1 университет",
  "Muammo": "Мәселе", "Nazariya bor. Isbot yo'q.": "Теория бар. Дәлил жоқ.",
  "problem_p": "Питириўшилер «тәжирийбе жоқ» дегени ушын жумысқа алынбайды, жумыс бериўшилер болса «тәжирийбели кандидат жоқ» деп айлап излейди. KASBORA дәл усы аралықты — дәлилленген тәжирийбе жетиспеўшилигин жабады.",
  "s1": "жумыс бериўшилер питириўшилерде әмелий көнликпе жетиспейтуғынын айтады",
  "s2": "биринши жумыс излеўдиң орташа мүддети (тәжирийбесиз питириўши)",
  "s3": "тезирек сәўбетке шекем — CV саралаў орнына тастыйықланған паспорт",
  "s4": "пилот мақсети: Verified-to-Hired Rate — тийкарғы метрика",
  "pilot_note": "* 2025-жыл Ташкент пилот изертлеўи, n=40 жумыс бериўши",
  "KASBORA jarayoni": "KASBORA процесси", "Bilimdan ishga — olti bosqich": "Билимнен жумысқа — алты басқыш",
  "st1_t": "01 · Үйрениў", "st1_d": "Университеттеги билим KASBORA'да бағытқа айналады: Junior Frontend жолы ушын HTML, CSS, JavaScript, React, Git ҳәм REST API.",
  "st2_t": "02 · Дәлиллеў", "st2_d": "Ҳәр кәсип ушын ўақытлы баҳалаў: аралас тәртиптеги сорақлар, таб-алмастырыў бақлаўы, шекленген урыныслар. Өттиңиз бе — кәсип VERIFIED болады.",
  "st3_t": "03 · Практика", "st3_d": "Ментор тексеретуғын ҳақыйқый тапсырмалар: landing page, dashboard, API интеграция. Ҳәр бирине 0–100 балл ҳәм жазба пикир.",
  "st4_t": "04 · Қурыў", "st4_d": "Ҳақыйқый компанияның ҳақыйқый тапсырмасы: бриф, дедлайн, төлем, код шолыў. Тамамланған проект — жумыс бериўши рейтинги менен.",
  "st5_t": "05 · Тастыйықлаў — Кәсиплик паспорт", "st5_d": "Барлық дәлиллер бир ҳүжжетке жыйналады: тастыйықланған кәсиплер, проектлер, рейтинглер ҳәм ашық формула менен есапланған Work Readiness Score.",
  "st6_t": "06 · Жумысқа орналасыў", "st6_d": "Жумыс бериўши паспортты көреди → шортлист → соқыр шолыў → сәўбет → тапсырма → усыныс. Рәсмий шәртнаманы жумыс бериўши мәмлекетлик системада рәсмийлестиреди.",
  "Nazariya": "Теория", "Assessment": "Баҳалаў", "Mentor": "Ментор", "Kompaniya": "Компания", "Offer": "Усыныс",
  "Pilotdagi skill'lar": "Пилоттағы кәсиплер", "Har badge ortida — real isbot": "Ҳәр белги артында — ҳақыйқый дәлил",
  "skills_p": "Junior Frontend жолы ушын 6 кәсип. Ҳәр бири ўақытлы баҳалаў менен тексерилади — өтсеңиз, белгиңиз VERIFIED болып паспортыңызға басылады. Кәсипти басып, үлги сорақты көриң.",
  "verified": "тастыйықланған",
  "Eng muhim hujjat": "Ең әҳмийетли ҳүжжет", "Skill Passport — sizning isbotingiz": "Кәсиплик паспорт — сиздиң дәлилиңиз",
  "passport_p": "Ҳәр кәсип ушын кеминде бир дәлил дерги: баҳалаў, тапсырма, проект, ментор яки жумыс бериўши баҳасы. Паспортта ҳеш нәрсе жасырылмайды — Work Readiness Score ашық формула менен есапланады. Студентти таңлаң — паспорт жаныланады.",
  "Jonli passport'ni ochish →": "Жаны паспортты ашыў →", "O'zingiznikini quring": "Өзиңиздикин қурың",
  "QR-verifikatsiya": "QR-тастыйықлаў", "qr_d": "Жумыс бериўши кодты сканерлеп, паспортты KASBORA базасынан тексереды",
  "Anti-cheat monitoring": "Анти-алдаў бақлаўы", "ac_d": "Ўақытлы режим, аралас сорақлар, таб-алмастырыў ҳәм paste бақлаўы",
  "Mentor tasdig'i": "Ментор тастыйығы", "mt_d": "Ҳәр практика нәтийжеси жаны ментор тәрепинен тастыйықланады",
  "Interaktiv kalkulyator": "Интерактив калькулятор", "Yangi talaba": "Жаңа студент", "O'rtacha bitiruvchi": "Орташа питириўши", "KASBORA bitiruvchisi": "KASBORA питириўшиси",
  "c_assessment": "Баҳалаўлардың орташа баллы", "c_practice": "Практика тапсырмалары баллы", "c_project": "Ҳақыйқый проектлер баллы", "c_mentor": "Ментор пикири баллы", "c_employer": "Жумыс бериўши баҳасы баллы",
  "calc_note": "Ползунларды сүйрең — KASBORA баллды дәл усы ашық формула менен есаплайды. Жасырын алгоритм жоқ.",
  "calc_bands": "0–49 Басланғыш · 50–69 Раўажланбақта · 70–84 Жумысқа тайын · 85–100 Жоқары тайын",
  "Haqiqiy ovozlar": "Ҳақыйқый даўыслар", "Pilot ishtirokchilari nima deydi": "Пилот қатнасыўшылары не дейди",
  "t1": "CV жибериўди тоқтаттым. Баҳалаўлардан өттим, бир ҳақыйқый проект иследим — паспортымды көрген жумыс бериўши өзи жазды. Ҳәзир ABC Digital'да ислеймен.",
  "t2": "Аўал Telegram'да 300 CV саралайтуғын едим. Ҳәзир соқыр шолыўда тек кодты баҳалаймыз — аты да көринбейди. Жумысқа алыў ўақты 3 ҳәптеден 6 күнге түсти.",
  "t3": "KASBORA менторлықты өлшенетуғын етти: ҳәр тапсырыўға 5 өлшем бойынша балл беримен, студент өсиўин ҳақыйқый санларда көреди.",
  "EKOTIZIM": "ЭКОСИСТЕМА", "Platforma — veb-saytdan kattaroq": "Платформа — веб-сайттан үлкен", "Ekotizimni ko'rish →": "Экосистеманы көриў →",
  "e1_t": "Telegram Mini App", "e1_d": "Прогресс, баҳалаўлар ҳәм проектлер — Telegram ишинде, бир басыўда. Мобил қосымша жолда.",
  "e2_t": "Open API", "e2_d": "Паспорт тастыйықлаў, кандидат излеў ҳәм тайынлық endpoint'лери — HRIS ҳәм EduOS ушын.",
  "e3_t": "Төлем интеграциялары", "e3_d": "Проект төлемлери ҳәм жумыс бериўши тарифлери Click ҳәм Payme арқалы. Мәмлекетлик системалар изертленбекте.",
  "Savol-javob": "Сорақ-жуўап", "Ko'p beriladigan savollar": "Көп берилетуғын сорақлар",
  "f1q": "KASBORA жумыс табыў сайтынан неси менен парқланады?", "f1a": "Жумыс табыў сайтлары тек вакансия жәриялайды. KASBORA болса студентти жумысқа таярлайды: кәсиплер баҳалаў арқалы тастыйықланады, ҳақыйқый компания проектлеринде тәжирийбе жыйналады ҳәм ҳәммеси Кәсиплик паспортта дәлили менен көрсетиледи.",
  "f2q": "Кәсип қалай тастыйықланады (VERIFIED)?", "f2a": "Алты дерек бар: өзи билдирген, баҳалаў, практика тапсырмасы, ҳақыйқый проект, ментор ҳәм жумыс бериўши баҳасы. Тек кеминде бир дәлил дереги бар кәсип VERIFIED белгисин алады.",
  "f3q": "Кәсиплик паспорт жалғанлаўдан қалай қорғалған?", "f3a": "Ҳәр паспортта өзгеше QR код бар — жумыс бериўши кодты сканерлеп, мағлыўматларды KASBORA базасынан тексереды. Баҳалаўлар ўақытлы режимде, аралас сорақлар ҳәм таб-бақлаў менен өтеди.",
  "f4q": "Work Readiness Score қалай есапланады?", "f4a": "Толық ашық: Баҳалаў 30% + Практика 20% + Ҳақыйқый проектлер 30% + Ментор пикири 10% + Жумыс бериўши баҳасы 10%. Ҳеш қандай жасырын AI жоқ.",
  "f5q": "Соқыр шолыў не ҳәм неге керек?", "f5a": "Жумыс бериўши тапсырыўды кандидаттың аты, университети яки сүўретин көрмей баҳалайды — тек код ҳәм нәтийже. Бул әдалатлы таңлаўды тәмийинлейди.",
  "f6q": "Студентлер ушын бийпул ба?", "f6a": "MVP дәўиринде студентлер ушын толық бийпул. Жумыс бериўшилер проект жайластырыў ҳәм талантқа кириў ушын төлейди; университетлер студент санына қарап SaaS тарифинде ислейди.",
  "PILOT OCHIQ · TATU TALABALARI UCHIN": "ПИЛОТ АШЫҚ · TATU СТУДЕНТЛЕРИ УШЫН",
  "cta_h": "Карьераңызды бүгин дәлил менен баслаң.", "cta_p": "Биринши баҳалаў 10 минут. Биринши тастыйықланған кәсип — бүгин. Биринши ҳақыйқый проект — усы ҳәптеде.",
  "Start Your Career →": "Карьераны баслаў →", "Demo hisoblarni sinash": "Демо аккаунтларды сынаў",
  "Platforma": "Платформа", "Ishtirokchilar": "Қатнасыўшылар", "Huquqiy": "Ҳуқықый", "Ish beruvchilar": "Жумыс бериўшилер",
  "Universitetlar": "Университетлер", "Mentorlar": "Менторлар", "Demo kirish": "Демо кириў", "Maxfiylik siyosati": "Қупиялық сиясаты",
  "Shartlar": "Шәртлер", "Shaxsiy ma'lumotlar": "Жеке мағлыўматлар",
  "footer_about": "Университеттеги билимди ҳақыйқый тәжирийбеге, тастыйықланған кәсипке ҳәм рәсмий жумысқа айландыратуғын платформа.",
  "footer_rights": "© 2025 KASBORA · Өзбекстан ушын қурылмақта", "footer_mvp": "MVP: 1 кәсип · 1 университет · 10 компания",
  "Tajribani isbotlang": "Тәжирийбени дәлиллең", "bepul · 10 daqiqada boshlanadi": "бийпул · 10 минутта басланады",

  "aud_st_t": "Диплом емес — дәлилленген тәжирийбе", "aud_st_d2": "Басланғыш баҳалаў менен баслайсыз, ментор тексерген тапсырмалар ҳәм ҳақыйқый компания проектлери арқалы Кәсиплик паспорт қурасыз. Жумыс бериўши сизди CV бойынша емес, дәлил бойынша көреди.",
  "aud_em_t": "300 CV орнына — 12 тастыйықланған паспорт", "aud_em_d2": "Кәсип бойынша фильтрленген кандидатлар, соқыр шолыў (аты жасырылған, тек код баҳаланады), сәўбет ҳәм тапсырма pipeline'и бир панельде.",
  "aud_un_t": "Ҳәр студент қай жерде — ҳақыйқый санларда", "aud_un_d2": "Баҳалаў нәтийжелери, проект қатнасы, жумысқа орналасыў дәрежеси — ҳәммеси жаны панельде. CSV импорт арқалы студентлерди бир неше минутта қосасыз.",
  "Kandidatlar bazasini ko'rish →": "Кандидатлар базасын көриў →", "Track Student Readiness →": "Тайынлықты бақлаў →",
  "tk1": "Али Каримов JavaScript кәсипин тастыйықлады — 82/100", "tk2": "ABC Digital жаңа ҳақыйқый проект жәриялады: корпоратив landing page",
  "tk3": "Мадина Юсупова жумыс бериўши тапсырмасынан өтти — 91/100", "tk4": "TATU: усы ҳәптеде 12 баҳалаў тамамланды",
  "tk5": "Соқыр шолыў: 2 аноним тапсырыў баҳаланды", "tk6": "Али Каримов сәўбетке шақырылды", "tk7": "Жаңа ментор: Дилшод Раҳимов (Senior Frontend)",
  "Xush kelibsiz": "Хош келдиңиз", "Akkaunt yaratish": "Аккаунт жаратыў", "demo_h": "Демо аккаунтлар — бир басыў менен кириң",
  "demo_pass": "Барлық демо аккаунтлар ушын пароль:", "Email": "Email", "Parol": "Пароль", "Ism": "Аты", "Familiya": "Фамилиясы",
  "Universitet": "Университет", "Fakultet": "Факультет", "Yo'nalish": "Бағыт", "Bitiruv yili": "Питириў жылы",
  "Kompaniya nomi": "Компания аты", "Talaba": "Студент", "Akkauntingiz yo'qmi?": "Аккаунтыңыз жоқ па?", "Allaqachon akkauntingiz bormi?": "Аккаунтыңыз бар ма?",
  "err_fields": "Аты, фамилиясы, email ҳәм кеминде 6 белгили пароль киргизиң.", "err_email": "Бул email аллақашан дизимнен өткен.",
  "err_creds": "Email яки пароль қәте.", "reg_ok": "Аккаунт жаратылды! Биринши баҳалаўға тайынсыз ба?",
  "reg_employer_ok": "Жумыс бериўши аккаунты жаратылды. Тастыйықлаў админ тәрепинен қабыл етиледи.", "reg_uni_ok": "Университет аккаунты жаратылды.",
  "auth_side_h": "Диплом жеткиликли емес — тәжирийбени дәлиллең.", "auth_side_p": "Баҳалаў → практика тапсырмасы → ҳақыйқый проект → кәсиплик паспорт → жумыс бериўши. Ҳәр басқыш профилиңизде дәлили менен қалады.",
  "err_org": "Компания яки университет атын киргизиң.",
  "pp_pub": "Ашық кәсиплик паспорт", "PDF eksport": "PDF экспорт", "Link nusxalandi": "Силтеме көширилди",
  "Tasdiqlangan skill'lar": "Тастыйықланған кәсиплер", "Real loyihalar": "Ҳақыйқый проектлер", "employer ★": "жумыс бериўши ★",
  "real loyiha": "ҳақыйқый проект", "Mentor reytingi": "Ментор рейтинги", "pp_gen": "Бул паспорт KASBORA платформасындағы жаны жазыўлар тийкарында жаратылған.",
  "Topilmadi": "Табылмады", "pp_404": "Бул username ушын паспорт жоқ.", "self-declared": "өзи билдирген",
  "cj_t": "Кандидат жолы — сиздиң жолыңыз", "Baseline": "Басланғыш", "Birinchi assessment": "Биринши баҳалаў", "Verified skills": "Тастыйықланған кәсиплер",
  "tasdiqlangan": "тастыйықланған", "Hiring tracks": "Жумыс жоллары", "topshiriq o'tdi": "тапсырмадан өтти", "Readiness": "Тайынлық", "Interview": "Сәўбет",
  "Jarayonda": "Процесте", "Kutilmoqda": "Күтилип атыр", "Hired": "Жумысқа алынды", "Tabriklaymiz! 🎉": "Қутлықлаймыз! 🎉", "Maqsad": "Мақсет",
  "Work Readiness Score": "Жумысқа тайынлық баллы", "Ochiq formula: 30/20/30/10/10": "Ашық формула: 30/20/30/10/10", "Batafsil →": "Толығырақ →",
  "Verified skill'larim": "Тастыйықланған кәсиплерим", "Hali verified skill yo'q": "Ҳәзирше тастыйықланған кәсип жоқ",
  "dash_empty_b": "Биринши баҳалаўды тапсырың — кәсип бирден VERIFIED болады.", "Assessment topshirish": "Баҳалаў тапсырыў",
  "So'nggi bildirishnomalar": "Соңғы хабарламалар", "quick1_d": "Ўақытлы · аралас · анти-алдаў", "Loyiha topish": "Проект табыў",
  "ta ochiq loyiha": "ашық проект", "Passport qurish": "Паспорт қурыў", "quick3_d": "QR + PDF экспорт",
  "ac_note": "Анти-алдаў: таймер · аралас сорақлар · таб-бақлаў · paste журналы · максимум", "urinish. O'tish balli — 70.": "уриныс. Өтиў баллы — 70.",
  "O'tish balli": "Өтиў баллы", "skill_verified_note": "кәсипи паспортыңызға VERIFIED болып басылады.", "Urinishlar": "Урыныслар", "eng yaxshi": "ең жақсы",
  "Urinishlar tugadi": "Урыныслар тамам болды", "Qayta topshirish": "Қайта тапсырыў", "Yana urinish": "Және урыныў",
  "Savol": "Сорақ", "Oldingi": "Алдыңғы", "Keyingi": "Кейинги", "Yakunlash ✓": "Тамамлаў ✓", "Assessment yakunlandi": "Баҳалаў тамамланды",
  "Tabriklaymiz — o'tdingiz!": "Қутлықлаймыз — өттиңиз!", "Bu safar o'ta olmadingiz": "Бул жолы өте алмадыңыз",
  "skill VERIFIED bo'ldi": "кәсипи VERIFIED болды", "Qayta tayyorlanib, yana urinib ko'ring": "Қайта таярланып, және урынып көриң",
  "tab_warn": "мәрте басқа айнаға өттиңиз — бул қағыйда журналында жазылды.", "Dashboard'ga qaytish": "Панельге қайтыў",
  "Vaqt tugadi — javoblar yuborildi": "Ўақыт тамам болды — жуўаплар жиберилди",
  "hiring track": "жумыс жолы", "Submission yuborish →": "Тапсырыў жиберiw →", "izoh_hint": "Не иследиңиз, қалай қарам-қатнас жасадыңыз?",
  "Live preview URL": "Жаны көрсетиў URL", "live_hint": "Vercel/Netlify deploy силтемеси — жумыс бериўши көреди",
  "Topshiriq yuborildi — mentor tekshiradi": "Тапсырыў жиберилди — ментор тексереды", "Kamida 10 belgi izoh yozing": "Кеминде 10 белги изah жазың",
  "Topshirildi": "Тапсырылды", "mentor tekshiruvida": "ментор тексериўинде", "deadline": "дедлайн",
  "Apply →": "Арза бериў →", "Ariza berilgan ✓": "Арза берилди ✓", "Cover message *": "Арза хаты *", "cover_hint": "Неге дәл сиз? Паспортыңыздағы дәлиллерге сүйениң.",
  "Ariza yuborish ✓": "Арза жиберiw ✓", "Ariza yuborildi! Employer ko'rib chiqadi": "Арза жиберилди! Жумыс бериўши көрип шығады",
  "err_cover": "Арза хаты кеминде 20 белги болсын", "Ochiq loyihalar yo'q": "Ашық проектлер жоқ",
  "Arizalar yo'q": "Арзалар жоқ", "appl_empty_b": "Ашық проектлерге арза бериң — статус усы жерде көринеди.", "Loyihalarni ko'rish": "Проектлерди көриў",
  "Loyiha progressi": "Проект прогресси", "Workspace": "Жумыс майданы", "ws_note": "бриф, тапсырмалар ҳәм ментор тексериўлери — жумыс бериўши жумыс майданын жаратты.",
  "Interview yo'q": "Сәўбет жоқ", "int_empty_b": "Жумыс бериўши сизди сәўбетке шақырғанда усы жерде көресиз.",
  "Qabul qilish ✓": "Қабыл етиў ✓", "Interview tasdiqlandi": "Сәўбет тастыйықланды", "Rad etildi": "Қабыл етилмеди",
  "Employer topshiriqlari": "Жумыс бериўши тапсырмалары", "Ish takliflari": "Жумыс усыныслары", "off_empty_t": "Жумыс бериўши процесси ҳәзирше басланбаған",
  "off_empty_b": "Сәўбеттен кейин жумыс бериўши тапсырмасы ҳәм усыныс усы жерде пайда болады.", "Offerni qabul qilish 🎉": "Усынысты қабыл етиў 🎉",
  "hired_toast": "Қутлықлаймыз — сиз жумысқа қабыл етилдиңиз! 🎉", "legal_note": "Рәсмий процесс: жумыс бериўши мийнет шәртнамасын электрон мәмлекетлик системада рәсмийлестиреди. KASBORA тек статусды бақлайды.",
  "Yechim tavsifi / PR linki": "Шешим сүўретлемеси / PR силтемеси", "Kamida 10 belgi yozing": "Кеминде 10 белги жазың",
  "Employer task yuborildi": "Жумыс бериўши тапсырмасы жиберилди", "Kandidat topshirig'ini kutmoqda...": "Кандидаттың тапсырыўы күтилип атыр...",
  "Baholash mezonlari": "Баҳалаў өлшемлери",
  "Score qanday hisoblandi — shaffof formula": "Балл қалай есапланды — ашық формула",
  "Practice topshiriqlar": "Практика тапсырмалары", "Mentor feedback": "Ментор пикири", "Employer feedback": "Жумыс бериўши баҳасы",
  "Ommaviy passport": "Ашық паспорт", "Ko'rinishni o'zgartirish": "Көринисти өзгертиў", "Skill'larim": "Кәсиплерим",
  "Passport'ni ochish →": "Паспортты ашыў →", "skill_empty": "Ҳәзирше кәсип жоқ — баҳалаў тапсырың.", "Ko'rinish": "Көринис",
  "Employer AI Dashboard": "Жумыс бериўши AI панели", "ai_d": "Воронка, ўақыт ҳәм қәрежет — жаны есап. Telegram'дағы 300 CV емес, тек дәлилленген паспортлар.",
  "Kandidatlar bazasi": "Кандидатлар базасы", "Time-to-hire": "Жумысқа алыў ўақты", "6 kun": "6 күн", "cv_note": "CV саралаўда 21 күн еди",
  "Tejalgan xarajat": "Үнемленген қәрежет", "1.8 mln": "1,8 млн", "fee_note": "сом — агентлик төлемлерисиз", "Verified kandidat": "Тастыйықланған кандидатлар",
  "passport_filter": "паспорт бойынша фильтрленген", "Hired (pilot)": "Жумысқа алынған (пилот)", "contract_soon": "рәсмий шәртнама жолда",
  "Hiring voronkasi — Applied → Hired": "Жумысқа алыў воронкасы — Applied → Hired", "Tezkor amallar": "Тез әмеллер",
  "Yangi loyiha yaratish": "Жаңа проект жаратыў", "brief_skills": "бриф + кәсип талаплары", "Blind review navbati": "Соқыр шолыў гезеги",
  "ta anonim submission": "аноним тапсырыў", "Interview belgilash": "Сәўбет белгилеў", "kandidat_tanlang": "кандидатты таңлаң",
  "Offer yuborish": "Усыныс жиберiw", "task_passed": "тапсырмадан өткен кандидатларға",
  "Loyihalaringiz": "Проектлериңиз", "Loyiha yaratish": "Проект жаратыў", "Loyihalar yo'q": "Проектлер жоқ",
  "pr_empty_b": "Биринши ҳақыйқый проектыңызды жаратың — студентлер арза береды.", "Admin tasdig'ida": "Админ тастыйығында",
  "Loyiha yopildi": "Проект жабылды", "Yangi loyiha": "Жаңа проект", "Sarlavha": "Атама", "Tavsif": "Сүўретлеме",
  "Kerakli skill'lar": "Керекли кәсиплер", "Daraja": "Дәреже", "Davomiylik (kun)": "Даўамлылық (күн)", "To'lov (so'm)": "Төлем (сом)",
  "O'rinlar soni": "Орынлар саны", "Yaratish (admin tasdig'iga yuboriladi)": "Жаратыў (админ тастыйығына жибериледи)",
  "err_project": "Атама (5+ белги) ҳәм кеминде 1 кәсип таңлаң", "created_ok": "Проект жаратылды — админ тастыйығынан кейин жәрияланады",
  "Skill (verified)": "Кәсип (тастыйықланған)", "Min readiness": "Мин тайынлық", "ta kandidat topildi": "кандидат табылды",
  "verified_only": "тек тастыйықланған кәсиплер бойынша", "Passport'ni ko'rish": "Паспортты көриў",
  "empty_cand_t": "Фильтрге сәйкес кандидат табылмады", "empty_cand_b": "Фильтрлерди жумсартың яки мин тайынлық шегин төменлетиң.",
  "Blind Review Panel": "Соқыр шолыў панели", "blind_d": "Әдалатлы таңлаў: аты, университети ҳәм сүўрети жасырылған. Тек код ҳәм нәтийже баҳаланады.",
  "Anonim submission": "Аноним тапсырыў", "shaxs yashirilgan": "жеке тұлға жасырылған", "O'rtacha": "Орташа", "Shaxs ochildi": "Жеке тұлға ашылды",
  "anonim": "аноним", "Bahoingiz": "Баҳаңыз", "Bahoni yozish": "Баҳаны жазыў", "Shaxsni ochish": "Жеке тұлғаны ашыў",
  "blind_tip": "Усыныс: кеминде 2 баҳа жазылғаннан кейин ашың — әдалатлылық усы.",
  "reveal_t": "Жеке тұлғаны ашыўдан алдын баҳаларыңыз жазылған болыўы керек — бул әдалатлылық кепили.",
  "Hozir yozilgan baholar": "Ҳәзир жазылған баҳалар", "Baribir ochish": "Бәрибир ашыў", "shaxs_ochildi_d": "Жеке тұлға ашылды — паспортқа өтиң",
  "empty_blind_t": "Тапсырыўлар жоқ", "empty_blind_b": "Кандидатлар жумыс бериўши тапсырмасын тапсырғанда усы жерде аноним көринеди.",
  "Kamida 5 belgili izoh yozing": "Кеминде 5 белгили изah жазың", "Baho yozildi — shaxs hali yashirin": "Баҳа жазылды — жеке тұлға ҳәзирше жасырын",
  "Interview'ga taklif": "Сәўбетке шақырыў", "Invite to Interview": "Сәўбетке шақырыў", "Interviewlar yo'q": "Сәўбетлер жоқ",
  "int_empty_e": "Кандидатларды сәўбетке шақырың — Meet/Zoom силтемеси жеткиликли.", "Interview taklifi": "Сәўбет шақырыўы",
  "Taklif yuborish": "Шақырыў жиберiw", "Interview taklifi yuborildi": "Сәўбет шақырыўы жиберилди", "Yakunlandi": "Тамамланды",
  "Interview yakunlandi": "Сәўбет тамамланды", "Kandidatni tanlang": "Кандидатты таңлаң",
  "Create Employer Task": "Жумыс бериўши тапсырмасын жаратыў", "Topshiriqlar yo'q": "Тапсырмалар жоқ",
  "et_empty_b": "Сәўбеттен кейин кандидатларға киши ҳақыйқый тапсырма бериң — нәтийжени усы жерде баҳалайсыз.",
  "Yangi employer task": "Жаңа жумыс бериўши тапсырмасы", "Kandidat va sarlavha kiriting": "Кандидат ҳәм атама киргизиң",
  "Submission baholash": "Тапсырыўды баҳалаў", "Feedback yozing": "Пикир жазың", "Baho yuborildi": "Баҳа жиберилди", "Submission": "Тапсырыў",
  "Offerlar yo'q": "Усыныслар жоқ", "of_empty_b": "Тапсырма яки сәўбеттен өткен кандидатларға усыныс жиберің.", "Pozitsiya": "Лаўазым",
  "Oylik": "Айлық", "Xabar": "Хабар", "Interview/task o'tganlar ro'yxati": "Сәўбет/тапсырмадан өткенлер дизими",
  "Avval interview yoki task o'tkizing": "Аўал сәўбет яки тапсырма өткериң", "Offer yuborildi!": "Усыныс жиберилди!",
  "legal_employer": "Мийнет шәртнамасын электрон мәмлекетлик системада рәсмийлестириң — платформа тек статусды бақлайды.",
  "Kompaniya verifikatsiyasi kutilmoqda.": "Компания тастыйықлаўы күтилип атыр.", "ver_note": "KASBORA админ аккаунтты тастыйықлағаннан кейин проектлериңиз жәрияланады.",
  "Mentor tekshiruv paneli": "Ментор тексериў панели", "mentor_d": "5 өлшем бойынша баҳа + жазба пикир — нәтийже студент паспортына түседи.",
  "Navbat bo'sh": "Гезек бос", "mentor_empty_b": "Студентлер тапсырыў жибергени менен усы жерде пайда болады.",
  "Tekshirish va feedback": "Тексериў ҳәм пикир бериў", "Feedback berish": "Пикир бериў", "Texnik sifat": "Техникалық сапа",
  "Kommunikatsiya": "Байланыс", "Muammoni yechish": "Мәселени шешим", "Deadline'ga rioya": "Дедлайнға әмел етиў",
  "Jamoa bilan ishlash": "Команда менен ислесиў", "Umumiy": "Улыўма", "PASSED bo'ladi": "PASSED болады", "FAILED bo'ladi": "FAILED болады",
  "fb_placeholder": "Күшли тәреплери ҳәм өсиў нуқатлары...", "Feedback yuborish": "Пикир жиберiw",
  "fb_ok": "Пикир жиберилди — паспортқа қосылды", "Yakunlangan feedbacklar": "Тамамланған пикирлер", "Hozircha feedback yo'q": "Ҳәзирше пикир жоқ",
  "fb_empty_b": "Гезектеги тапсырмаларды тексериң — нәтийжелер усы жерде қалады.",
  "Jami talabalar": "Жәми студентлер", "Assessment yakunlagan": "Баҳалаўды тамамлаған", "Real loyiha qatnashchisi": "Ҳақыйқый проект қатнасыўшысы",
  "Ishga joylashgan": "Жумысқа орналасқан", "O'rtacha Work Readiness": "Орташа жумысқа тайынлық", "Employment rate": "Жумыс пенен тәмийинлеў дәрежеси",
  "Import qilish": "Импорт етиў", "import_ok": "2 студент аккаунты жаратылды", "edu_note": "EduOS/SIS API интеграциясы жолда — ҳәзирше CSV.",
  "Skill bo'yicha o'rtacha ball": "Кәсип бойынша орташа балл", "Employment voronkasi": "Жумысқа орналасыў воронкасы",
  "North Star: Verified-to-Hired Rate": "North Star: Verified-to-Hired Rate",
  "north_star_d": "Тастыйықланған тәжирийбе алған студентлердиң нешеўи жумысқа кирди — стартаптың ҳақыйқый баҳасы усы метрикада.",
  "uni_t": "TATU — Университет панелі", "uni_d": "Студентлер тайынлығын реал ўақытта бақлаң.",
  "Tasdiqlash kutilmoqda": "Тастыйықлаў күтилип атыр", "admin_no_projects": "Күтилип атырған проектлер жоқ.", "E'lon qilingan": "Жәрияланған",
  "Loyiha tasdiqlandi va e'lon qilindi": "Проект тастыйықланды ҳәм жәрияланды", "Loyiha rad etildi": "Проект қабыл етилмеди",
  "Verifikatsiya kutilmoqda": "Тастыйықлаў күтилип атыр", "verifikatsiya qilindi": "тастыйықланды", "BLOKLANGAN": "БЛОКЛАНҒАН",
  "Bloklash": "Блоклаў", "Blokdan chiqarish": "Блоктан шығарыў", "Bloklandi": "Блокланды", "Blokdan chiqarildi": "Блоктан шығарылды",
  "Skill tahrirlash": "Кәсипти өзгертиў", "Nomi": "Аты", "Skill saqlandi": "Кәсип сақланды",
  "KASBORA ekotizimi": "KASBORA экосистемасы", "← Bosh sahifa": "← Бас бет", "eco_h": "Платформа — веб-сайттан үлкен",
  "eco_p": "Telegram Mini App, Open API ҳәм төлем/билимлендириў интеграциялары KASBORA'ны бирден-бир талант инфраструктурасына айландырады.",
  "PILOTDA JONLI": "ПИЛОТТА ЖАНЫ", "MOBIL": "МОБИЛ", "eco_tg_h": "Telegram Mini App — прогресс қалтаңызда",
  "eco_tg_p": "Өзбекстанда Telegram — тийкарғы канал. Студент баҳалаў нәтийжесин, сәўбет шақырыўын ҳәм проект жаңалықларын бот арқалы алады.",
  "tg1_t": "Реал ўақыттағы хабарламалар", "tg1_d": "сәўбет, нәтийже, пикир — push арқалы", "tg2_t": "Telegram'да баҳалаў", "tg2_d": "MCQ сорақлар бот ишинде, таймер менен",
  "tg3_t": "iOS/Android қосымша жолда", "tg3_d": "PWA аллақашан ислейди, native — 2-басқыш", "eco_bot": "пилот ушын ашық · /start менен басланады",
  "API key": "API key", "Misol — passport verifikatsiya kodi": "Мысал — паспорт тастыйықлаў коды",
  "Integratsiyalar": "Интеграциялар", "int_d": "Базарға терең байланыс", "JONLI": "ЖАНЫ", "YO'LDA": "ЖОЛДА", "REJA": "РЕЖЕ", "PILOT": "ПИЛОТ",
  "i_click": "Проект төлемлери ҳәм тарифлер — пилотта жалғанған", "i_tg": "Хабарлама, баҳалаў ҳәм Mini App каналы",
  "i_eduos": "Университет LMS менен студент синхронизациясы (ҳәзирше CSV)", "i_hris": "Жумысқа алынған кандидатларды 1C:ZUP'қа экспорт",
  "i_gov": "Электрон мийнет шәртнамасы — ҳуқықый экспертиза басқышы", "i_api": "Паспорт, кандидат ҳәм тайынлық endpoint'лери",
  "i_mail": "Баҳалаў, усыныс ҳәм пикир хабарлары", "i_push": "Мобил қосымша менен бирге, 2-басқыш",
  "Roadmap": "Жол картасы", "rm_d": "Не қашан келеди", "rm1_p": "1-БАСКЫШ · Ҳәзир", "rm1_t": "MVP — дәлиллеў", "rm2_p": "2-БАСКЫШ · 3–6 ай",
  "rm2_t": "Кеңейтиў", "rm3_p": "3-БАСКЫШ · 6–12 ай", "rm3_t": "Инфраструктура",
  "rm1_1": "Auth + 5 роль панели", "rm1_2": "Баҳалаў двигатели (анти-алдаў)", "rm1_3": "Ҳақыйқый проектлер + Соқыр шолыў", "rm1_4": "Кәсиплик паспорт + QR", "rm1_5": "Telegram бот (пилот)",
  "rm2_1": "Native мобил қосымша", "rm2_2": "EduOS/SIS API интеграциясы", "rm2_3": "AI пикир генераторы", "rm2_4": "Толық Click/Payme ағымы", "rm2_5": "Жаңа кәсиплер (QA, Design)",
  "rm3_1": "Университет SaaS", "rm3_2": "Санлы сертификатлар", "rm3_3": "my.gov.uz изертлеўи", "rm3_4": "API маркетплейси", "rm3_5": "Аймақлық кеңейиў",
  "Demo kirish →": "Демо кириў →", "demo_login_d": "Демо аккаунтлар арқалы 5 ролди де сынап көриң — пароль:", "Bosh sahifa": "Бас бет",
  "Bugungi progress": "Бүгинги прогресс", "Keyingi assessment →": "Кейинги баҳалаў →", "wr_phone": "Жумысқа тайын · +6 усы ҳәптеде",
  "Loyiha": "Проект", "review'da": "тексериўде",
  "proc_p": "KASBORA-da student jay ǵana dizimnen ótpеydi — ol tolıq shınjırdan ótedi: bahalawlar menen dálillengen bilim, mentor tekseriwleri, haqıyqıy kompaniya proyektlerinde islew hám barlıq nátiyjeler Kásiplik pasportta jıynaladı. Jumıs beriwshi rezume emes, dálil kóredi.",
  "proc_lifecycle": "Kandidattıń ómirlik ciklı — jumısqa alıw ворonkası",
  "proc_lifecycle_d": "Hár bir ariza usı shınjır boyı menen háreket etedi. Student jaǵdaydı real waqıtta kóredi, jumıs beriwshi hár basqıshta tek dálillengen nátiyjeler menen isleydi.",
  "proc_reject": "Qálegen basqıshta rad etilse",
  "sk_sources_h": "6 dálil dáregi", "isbot_emas": "dálil emes", "sk_levels_h": "Kásip dárejesi",
  "sk_levels_d": "Dáreje bahalaw ballına qaray avtomat beriledi hám hár jańa dálil menen jańalanadı — pasport hámiyshe eń kúshli dárekti kórsetedi.",
  "pp_bands_h": "Work Readiness shkalası",
  "pp_b1": "Joldıń basında — birinshi bahalaw kútilmekte.",
  "pp_b2": "Kásipler qáliplespekte — ámeliy tapsırmalar kerek.",
  "pp_b3": "Jumıs beriwshiler kóredi: sáwbetke tayar kandidat.",
  "pp_b4": "Joqarı talap — haqıyqıy proekt tájiriybesi menen.",
  "faq_contact": "Basqa sorawlarıńız barma?",
  "faq_contact_d": "Pilot komandası is kúnleri 2 saat ishinde juwap beredi. Telegram bot arqalı da jazıwǵa boladı.",
  "full_read": "Tolıq bólimdi ashıw",
  "idx_h": "Tereńirek biliń",
  "idx_t": "KASBORA'nı jaqınıraq tanıń",
  "idx_p": "Process, kásipler, kásiplik pasport hám soraw-juwap — hárbiri óziniń tolıq betinde. Qızıqqanın ashıń.",
  "idx_proc_d": "Bilimnen jumısqa — 6 basqıshtıń tolıq jolı hám kandidattı воронkası qalay isleydi.",
  "idx_sk_d": "Pilottаǵı 8 kásip, olardıń dálil derekleri hám dárejeleri.",
  "idx_pp_d": "Eń áhmiyetli hújjet — QR verifikaciya, anti-cheat hám ashıq tayınlıq formulası.",
  "idx_faq_d": "Eń kóp beriletuǵın sorawlar hám anıq juwaplar.",
  "6 bosqich": "6 basqısh", "8 skill": "8 kásip", "QR + PDF": "QR + PDF", "6 savol": "6 soraw",
};
