export const DICT_TR: Record<string, string> = {
  "Kirish": "Giriş yap", "Boshlash →": "Başla →", "Ro'yxatdan o'tish": "Kayıt ol", "Jarayon": "Süreç",
  "Skill Passport": "Beceri Pasaportu", "Ekotizim": "Ekosistem", "FAQ": "SSS", "Til": "Dil",
  "Yorug' rejim": "Açık tema", "Tun rejimi": "Koyu tema", "Bildirishnomalar": "Bildirimler",
  "Hozircha bildirishnoma yo'q": "Henüz bildirim yok", "Hammasini o'qildi deb belgilash": "Tümünü okundu işaretle",
  "Chiqish": "Çıkış yap", "Menyu": "Menü", "Passport": "Pasaport", "Yopish": "Kapat", "Bekor qilish": "İptal",
  "Saqlash": "Kaydet", "Tahrirlash": "Düzenle", "Tasdiqlash": "Onayla", "Rad etish": "Reddet", "Barchasi": "Tümü",
  "Shahar": "Şehir", "Tozalash": "Temizle", "Izoh": "Yorum", "Sana": "Tarih", "Vaqt": "Saat", "Turi": "Tür",
  "Kandidat": "Aday", "Tanlang...": "Seçin...", "Yuborish": "Gönder", "Baholash": "Değerlendir", "Jami": "Toplam",
  "Video": "Video", "Ofisda": "Ofiste", "Telefon": "Telefon", "kun": "gün", "ariza": "başvuru", "navbatda": "sırada",
  "baho": "puan", "readiness": "hazırlık", "savol": "soru", "daqiqa": "dk", "o'rin": "pozisyon", "Namuna savol": "Örnek soru",
  "tez kunda": "yakında", "Yuqori tayyor": "Yüksek hazırlık", "Ishga tayyor": "İşe hazır", "Rivojlanmoqda": "Gelişiyor", "Boshlang'ich": "Başlangıç",
  "Talaba paneli": "Öğrenci paneli", "Employer paneli": "İşveren paneli", "Mentor paneli": "Mentor paneli",
  "Universitet paneli": "Üniversite paneli", "Admin panel": "Yönetici paneli",
  "Dashboard": "Panel", "Assessmentlar": "Değerlendirmeler", "Practice tasks": "Pratik görevler", "Loyihalar": "Projeler",
  "Arizalarim": "Başvurularım", "Interviewlar": "Mülakatlar", "Offerlar": "Teklifler", "AI Dashboard": "AI Panel",
  "Kandidatlar": "Adaylar", "Blind Review": "Kör İnceleme", "Tasklar": "Görevler", "Tekshirish navbati": "İnceleme sırası",
  "Feedbacklar": "Geri bildirimler", "Talabalar": "Öğrenciler", "Analytics": "Analitik", "Foydalanuvchilar": "Kullanıcılar",
  "Skill katalogi": "Beceri kataloğu", "Audit log": "Denetim kaydı",
  "PILOT · TATU × 10 KOMPANIYA": "PİLOT · TATU × 10 ŞİRKET", "1 kasb: Junior Frontend Developer": "1 meslek: Junior Frontend Developer",
  "Diplom yetarli emas.": "Diploma yetmez.", "Tajribani isbotlang.": "Deneyiminizi kanıtlayın.",
  "hero_sub": "KASBORA öğrencileri gerçek projeler, doğrulanmış beceriler ve işverenlerle buluşturarak üniversiteden işe giden yolu kısaltır. CV'deki vaatler değil — kanıtlanmış deneyim.",
  "Talaba sifatida boshlash": "Öğrenci olarak başla", "aud_st_d": "Değerlendirme · proje · pasaport",
  "Ish beruvchi sifatida qo'shilish": "İşveren olarak katıl", "aud_em_d": "Doğrulanmış yetenek · gerçek proje · işe alım",
  "Universitet sifatida hamkorlik": "Üniversite olarak iş birliği", "aud_un_d": "Öğrenci hazırlığını gerçek zamanlı izleyin",
  "1 universitet · pilot": "1 üniversite · pilot", "10 kompaniya · real loyihalar": "10 şirket · gerçek projeler", "100+ talaba · birinchi oqim": "100+ öğrenci · ilk kohort",
  "Talaba yo'li — jonli simulyatsiya": "Öğrenci yolculuğu — canlı simülasyon",
  "O'rganish": "Öğren", "Isbotlash": "Kanıtla", "Amaliyot": "Pratik", "Real loyiha": "Gerçek proje", "Pasport": "Pasaport",
  "Ish beruvchi": "İşveren", "Suhbat": "Mülakat", "Task": "Görev", "Ishga joylashish": "İşe yerleşme",
  "OFFER QABUL QILINDI → HIRED": "TEKLİF KABUL EDİLDİ → İŞE ALINDI",
  "Pilotda ishtirok etayotganlar": "Pilot katılımcıları", "10 kompaniya · 1 universitet": "10 şirket · 1 üniversite",
  "Muammo": "Sorun", "Nazariya bor. Isbot yo'q.": "Teori var. Kanıt yok.",
  "problem_p": "Mezunlar «deneyim yok» diye işe alınmıyor, işverenler «deneyimli aday yok» diye aylarca arıyor. KASBORA tam bu boşluğu kapatır — kanıtlanmış deneyim eksikliğini.",
  "s1": "işveren, mezunlarda pratik beceri eksikliği olduğunu söylüyor", "s2": "ortalama ilk iş arama süresi (deneyimsiz mezun)",
  "s3": "mülakata daha hızlı — CV eleme yerine doğrulanmış pasaport", "s4": "pilot hedefi: Verified-to-Hired Rate — kuzey yıldızı metrik",
  "pilot_note": "* 2025 Taşkent pilot araştırması, n=40 işveren",
  "KASBORA jarayoni": "KASBORA süreci", "Bilimdan ishga — olti bosqich": "Bilgiden işe — altı adım",
  "st1_t": "01 · Öğren", "st1_d": "Üniversite bilgisi KASBORA'da bir yol olur: Junior Frontend için HTML, CSS, JavaScript, React, Git ve REST API.",
  "st2_t": "02 · Kanıtla", "st2_d": "Her beceri için süreli değerlendirme: karışık sorular, sekme takibi, sınırlı deneme. Geçtiniz — beceri VERIFIED.",
  "st3_t": "03 · Pratik", "st3_d": "Mentorun incelediği gerçek ödevler: landing page, dashboard, API entegrasyonu. Her birine 0–100 puan ve yazılı geri bildirim.",
  "st4_t": "04 · İnşa et", "st4_d": "Gerçek şirketten gerçek görev: brief, teslim tarihi, ödeme, kod incelemesi. Tamamlanan proje — işveren puanıyla.",
  "st5_t": "05 · Doğrula — Beceri Pasaportu", "st5_d": "Tüm kanıtlar tek belgede: doğrulanmış beceriler, projeler, puanlar ve açık formülle hesaplanan Work Readiness Score.",
  "st6_t": "06 · İşe yerleş", "st6_d": "İşveren pasaportu görür → kısa liste → kör inceleme → mülakat → işveren görevi → teklif. Resmî sözleşmeyi işveren devlet sisteminde düzenler.",
  "Nazariya": "Teori", "Assessment": "Değerlendirme", "Mentor": "Mentor", "Kompaniya": "Şirket", "Offer": "Teklif",
  "Pilotdagi skill'lar": "Pilottaki beceriler", "Har badge ortida — real isbot": "Her rozetin arkasında — gerçek kanıt",
  "skills_p": "Junior Frontend yolu için 6 beceri. Her biri süreli değerlendirmeyle test edilir — geçince rozetiniz VERIFIED olur ve pasaporta işlenir. Örnek soru için beceriye tıklayın.",
  "verified": "doğrulanmış",
  "Eng muhim hujjat": "En önemli belge", "Skill Passport — sizning isbotingiz": "Beceri Pasaportu — kanıtınız",
  "passport_p": "Her beceri için en az bir kanıt kaynağı: değerlendirme, görev, proje, mentor veya işveren puanı. Pasaportta hiçbir şey gizli değildir — Work Readiness Score açık formülle hesaplanır. Bir öğrenci seçin — pasaport canlı güncellenir.",
  "Jonli passport'ni ochish →": "Canlı pasaportu aç →", "O'zingiznikini quring": "Kendinizinkini oluşturun",
  "QR-verifikatsiya": "QR doğrulama", "qr_d": "İşveren kodu tarar ve pasaportu KASBORA veritabanından doğrular",
  "Anti-cheat monitoring": "Anti-cheat izleme", "ac_d": "Süreli mod, karışık sorular, sekme ve yapıştırma takibi",
  "Mentor tasdig'i": "Mentor onayı", "mt_d": "Her pratik sonucu canlı bir mentor tarafından onaylanır",
  "Interaktiv kalkulyator": "Etkileşimli hesaplayıcı", "Yangi talaba": "Yeni öğrenci", "O'rtacha bitiruvchi": "Ortalama mezun", "KASBORA bitiruvchisi": "KASBORA mezunu",
  "c_assessment": "Ortalama değerlendirme puanı", "c_practice": "Pratik görev puanı", "c_project": "Gerçek proje puanı", "c_mentor": "Mentor geri bildirim puanı", "c_employer": "İşveren geri bildirim puanı",
  "calc_note": "Kaydırıcıları oynatın — KASBORA puanı tam olarak bu şeffaf formülle hesaplar. Gizli algoritma yok.",
  "calc_bands": "0–49 Başlangıç · 50–69 Gelişiyor · 70–84 İşe hazır · 85–100 Yüksek hazırlık",
  "Haqiqiy ovozlar": "Gerçek sesler", "Pilot ishtirokchilari nima deydi": "Pilot katılımcıları ne diyor",
  "t1": "CV göndermeyi bıraktım. Değerlendirmeleri geçtim, bir gerçek proje yaptım — pasaportumu gören işveren bana kendisi yazdı. Şimdi ABC Digital'da çalışıyorum.",
  "t2": "Eskiden Telegram'da 300 CV ayıklardım. Şimdi kör incelemede sadece kodu değerlendiriyoruz — isimler görünmüyor. Time-to-hire 3 haftadan 6 güne düştü.",
  "t3": "KASBORA mentorluğu ölçülebilir yaptı: her çalışmayı 5 kritere göre puanlıyorum, öğrenciler gelişimi gerçek sayılarla görüyor.",
  "EKOTIZIM": "EKOSİSTEM", "Platforma — veb-saytdan kattaroq": "Platform bir web sitesinden büyük", "Ekotizimni ko'rish →": "Ekosistemi gör →",
  "e1_t": "Telegram Mini App", "e1_d": "İlerleme, değerlendirmeler ve projeler — Telegram içinde, tek dokunuşla. Mobil uygulama yolda.",
  "e2_t": "Open API", "e2_d": "Pasaport doğrulama, aday arama ve readiness uç noktaları — HRIS ve EduOS için.",
  "e3_t": "Ödeme entegrasyonları", "e3_d": "Click ve Payme ile proje ödemeleri ve işveren tarifeleri. Devlet sistemleri araştırılıyor.",
  "Savol-javob": "Soru-cevap", "Ko'p beriladigan savollar": "Sık sorulan sorular",
  "f1q": "KASBORA bir iş ilanı sitesinden nasıl farklı?", "f1a": "İş ilanı siteleri yalnızca ilan yayınlar. KASBORA öğrenciyi işe hazırlar: beceriler değerlendirmelerle doğrulanır, deneyim gerçek şirket projelerinde kazanılır ve hepsi kanıtlarıyla Beceri Pasaportu'nda gösterilir. İşveren CV değil, kanıt görür.",
  "f2q": "Beceri nasıl doğrulanır (VERIFIED)?", "f2a": "Altı kaynak: beyan, değerlendirme, pratik görev, gerçek proje, mentor ve işveren puanı. Yalnızca en az bir kanıt kaynağı olan beceri VERIFIED işaretini alır. «Beceriniz var» değil — «beceriniz var, işte kanıtı».",
  "f3q": "Beceri Pasaportu sahteciliğe karşı nasıl korunuyor?", "f3a": "Her pasaportun benzersiz bir QR kodu var — işveren kodu tarar ve verileri doğrudan KASBORA veritabanından kontrol eder. Değerlendirmeler süreli modda, karışık sorular ve sekme takibiyle yapılır; sonuçlar mentor ve işveren puanlarıyla güçlenir.",
  "f4q": "Work Readiness Score nasıl hesaplanır?", "f4a": "Tamamen şeffaf: Değerlendirme %30 + Pratik görevler %20 + Gerçek projeler %30 + Mentor geri bildirimi %10 + İşveren geri bildirimi %10. Kara kutu AI yok — her parça profilinizde görünür.",
  "f5q": "Kör inceleme nedir ve neden gerekir?", "f5a": "İşveren çalışmayı adayın adını, üniversitesini ve fotoğrafını görmeden puanlar — yalnızca kod ve sonuç. Bu adil seçimi garanti eder: fırsat isme değil, kanıta verilir.",
  "f6q": "Öğrenciler için ücretsiz mi?", "f6a": "MVP döneminde öğrenciler için tamamen ücretsiz. İşverenler proje yayınlama ve yetenek erişimi için öder; üniversiteler öğrenci başına SaaS tarifesi öder. Ödemeler Click ve Payme ile.",
  "PILOT OCHIQ · TATU TALABALARI UCHUN": "PİLOT AÇIK · TATU ÖĞRENCİLERİ İÇİN",
  "cta_h": "Kariyerinize bugün kanıtla başlayın.", "cta_p": "İlk değerlendirme 10 dakika. İlk doğrulanmış beceri — bugün. İlk gerçek proje — bu hafta.",
  "Demo hisoblarni sinash": "Demo hesapları dene",
  "Platforma": "Platform", "Ishtirokchilar": "Katılımcılar", "Huquqiy": "Hukuki", "Ish beruvchilar": "İşverenler",
  "Universitetlar": "Üniversiteler", "Mentorlar": "Mentorler", "Demo kirish": "Demo giriş", "Maxfiylik siyosati": "Gizlilik politikası",
  "Shartlar": "Şartlar", "Shaxsiy ma'lumotlar": "Kişisel veriler",
  "footer_about": "Üniversite bilgisini gerçek deneyime, doğrulanmış beceriye ve resmî işe dönüştüren platform.",
  "footer_rights": "© 2025 KASBORA · Özbekistan için inşa ediliyor", "footer_mvp": "MVP: 1 meslek · 1 üniversite · 10 şirket",
  "Tajribani isbotlang": "Deneyiminizi kanıtlayın", "bepul · 10 daqiqada boshlanadi": "ücretsiz · 10 dakikada başlar",

  "aud_st_t": "Diploma değil — kanıtlanmış deneyim", "aud_st_d2": "Temel değerlendirmeyle başlarsınız, mentor incelemeli görevler ve gerçek şirket projeleriyle Beceri Pasaportu inşa edersiniz. İşveren sizi CV ile değil, kanıtla görür.",
  "aud_em_t": "300 CV yerine — 12 doğrulanmış pasaport", "aud_em_d2": "Beceriye göre filtrelenmiş adaylar, kör inceleme (isimler gizli, yalnızca kod puanlanır), mülakat ve işveren görevi tek panelde. Time-to-hire düşer.",
  "aud_un_t": "Her öğrencinin seviyesi — gerçek sayılarla", "aud_un_d2": "Değerlendirme sonuçları, proje katılımı, istihdam oranı — hepsi canlı panelde. CSV içe aktarma ile öğrencileri SIS'ten dakikalar içinde ekleyin (EduOS entegrasyonu yolda).",
  "Kandidatlar bazasini ko'rish →": "Aday veritabanını gör →", "Track Student Readiness →": "Hazırlığı izle →",
  "tk1": "Ali Karimov JavaScript becerisini doğruladı — 82/100", "tk2": "ABC Digital yeni gerçek proje yayınladı: kurumsal landing page",
  "tk3": "Madina Yusupova işveren görevini geçti — 91/100", "tk4": "TATU: bu hafta 12 değerlendirme tamamlandı",
  "tk5": "Kör inceleme: 2 anonim çalışma puanlandı", "tk6": "Ali Karimov mülakata davet edildi", "tk7": "Yeni mentor: Dilshod Rahimov (Senior Frontend)",
  "Xush kelibsiz": "Tekrar hoş geldiniz", "Akkaunt yaratish": "Hesap oluştur", "demo_h": "Demo hesaplar — tek tıkla giriş",
  "demo_pass": "Tüm demo hesapların parolası:", "Email": "E-posta", "Parol": "Parola", "Ism": "Ad", "Familiya": "Soyad",
  "Universitet": "Üniversite", "Fakultet": "Fakülte", "Yo'nalish": "Uzmanlık", "Bitiruv yili": "Mezuniyet yılı",
  "Kompaniya nomi": "Şirket adı", "Talaba": "Öğrenci", "Akkauntingiz yo'qmi?": "Hesabınız yok mu?", "Allaqachon akkauntingiz bormi?": "Zaten hesabınız var mı?",
  "err_fields": "Ad, soyad, e-posta ve en az 6 karakterli parola girin.", "err_email": "Bu e-posta zaten kayıtlı.",
  "err_creds": "E-posta veya parola hatalı.", "reg_ok": "Hesap oluşturuldu! İlk değerlendirmeye hazır mısınız?",
  "reg_employer_ok": "İşveren hesabı oluşturuldu. Doğrulamayı yönetici onaylar.", "reg_uni_ok": "Üniversite hesabı oluşturuldu.",
  "auth_side_h": "Diploma yetmez — deneyiminizi kanıtlayın.", "auth_side_p": "Değerlendirme → pratik görev → gerçek proje → Beceri Pasaportu → işveren. Her aşama kanıtıyla profilinizde kalır.",
  "err_org": "Şirket veya üniversite adını girin.",
  "pp_rep": "ÖZBEKİSTAN CUMHURİYETİ", "pp_pub": "Herkese açık beceri pasaportu", "PDF eksport": "PDF dışa aktar", "Link nusxalandi": "Bağlantı kopyalandı",
  "Tasdiqlangan skill'lar": "Doğrulanmış beceriler", "Real loyihalar": "Gerçek projeler", "employer ★": "işveren ★",
  "real loyiha": "gerçek proje", "Mentor reytingi": "Mentor puanı", "pp_gen": "Bu pasaport KASBORA platformasının canlı kayıtlarından oluşturuldu.",
  "Topilmadi": "Bulunamadı", "pp_404": "Bu kullanıcı adına ait pasaport yok.", "self-declared": "beyan",
  "cj_t": "Candidate Journey — yolunuz", "Baseline": "Temel", "Birinchi assessment": "İlk değerlendirme", "Verified skills": "Doğrulanmış beceriler",
  "tasdiqlangan": "doğrulanmış", "Hiring tracks": "İşe alım yolları", "topshiriq o'tdi": "görev tamamlandı", "Readiness": "Hazırlık", "Interview": "Mülakat",
  "Jarayonda": "Sürüyor", "Kutilmoqda": "Beklemede", "Hired": "İşe alındı", "Maqsad": "Hedef",
  "Work Readiness Score": "Work Readiness Score", "Ochiq formula: 30/20/30/10/10": "Açık formül: 30/20/30/10/10", "Batafsil →": "Detay →",
  "Verified skill'larim": "Doğrulanmış becerilerim", "Hali verified skill yo'q": "Henüz doğrulanmış beceri yok",
  "dash_empty_b": "İlk değerlendirmeyi yapın — beceri anında VERIFIED olur.", "Assessment topshirish": "Değerlendirme yap",
  "So'nggi bildirishnomalar": "Son bildirimler", "Loyiha topish": "Proje bul", "ta ochiq loyiha": "açık proje",
  "Passport qurish": "Pasaport oluştur", "quick3_d": "QR + PDF dışa aktar",
  "ac_note": "Anti-cheat: süre · karışık sorular · sekme takibi · yapıştırma günlüğü · maks.", "urinish. O'tish balli — 70.": "deneme. Geçme puanı — 70.",
  "O'tish balli": "Geçme puanı", "skill_verified_note": "becerisi pasaporta VERIFIED olarak işlenir.", "Urinishlar": "Denemeler", "eng yaxshi": "en iyi",
  "Urinishlar tugadi": "Denemeler bitti", "Qayta topshirish": "Tekrar dene", "Yana urinish": "Bir daha dene",
  "Savol": "Soru", "Oldingi": "Geri", "Keyingi": "İleri", "Yakunlash ✓": "Bitir ✓", "Assessment yakunlandi": "Değerlendirme tamamlandı",
  "Tabriklaymiz — o'tdingiz!": "Tebrikler — geçtiniz!", "Bu safar o'ta olmadingiz": "Bu sefer geçemediniz",
  "skill VERIFIED bo'ldi": "becerisi VERIFIED oldu", "Qayta tayyorlanib, yana urinib ko'ring": "Hazırlanıp tekrar deneyin",
  "tab_warn": "kez başka pencereye geçtiniz — kural günlüğüne kaydedildi.", "Dashboard'ga qaytish": "Panele dön",
  "Vaqt tugadi — javoblar yuborildi": "Süre doldu — cevaplar gönderildi",
  "hiring track": "işe alım yolu", "Submission yuborish →": "Çalışma gönder →", "izoh_hint": "Ne yaptınız, yaklaşımınız neydi?",
  "Live preview URL": "Live preview URL", "live_hint": "Vercel/Netlify dağıtım bağlantısı — işveren görecek",
  "Topshiriq yuborildi — mentor tekshiradi": "Gönderildi — mentor inceleyecek", "Kamida 10 belgi izoh yozing": "En az 10 karakter yazın",
  "Topshirildi": "Gönderildi", "mentor tekshiruvida": "mentor incelemesinde", "deadline": "teslim",
  "Apply →": "Başvur →", "Ariza berilgan ✓": "Başvuruldu ✓", "Cover message *": "Ön yazı *", "cover_hint": "Neden siz? Pasaportunuzdaki kanıtlara dayanın.",
  "Ariza yuborish ✓": "Başvuruyu gönder ✓", "Ariza yuborildi! Employer ko'rib chiqadi": "Başvuru gönderildi! İşveren inceleyecek",
  "err_cover": "Ön yazı en az 20 karakter olmalı", "Ochiq loyihalar yo'q": "Açık proje yok",
  "Arizalar yo'q": "Başvuru yok", "appl_empty_b": "Açık projelere başvurun — durum burada görünür.", "Loyihalarni ko'rish": "Projeleri gör",
  "Loyiha progressi": "Proje ilerlemesi", "Workspace": "Workspace", "ws_note": "brief, görevler ve mentor kontrolleri — işveren workspace oluşturdu.",
  "Interview yo'q": "Mülakat yok", "int_empty_b": "İşveren sizi mülakata davet ettiğinde burada görürsünüz.",
  "Qabul qilish ✓": "Kabul et ✓", "Interview tasdiqlandi": "Mülakat onaylandı", "Rad etildi": "Reddedildi",
  "Employer topshiriqlari": "İşveren görevleri", "Ish takliflari": "İş teklifleri", "off_empty_t": "İşveren süreci henüz başlamadı",
  "off_empty_b": "Mülakattan sonra işveren görevi ve teklif burada görünür.", "Offerni qabul qilish 🎉": "Teklifi kabul et 🎉",
  "hired_toast": "Tebrikler — işe alındınız! 🎉", "legal_note": "Resmî süreç: işveren iş sözleşmesini elektronik devlet sisteminde düzenler. KASBORA yalnızca durumu izler.",
  "Yechim tavsifi / PR linki": "Çözüm açıklaması / PR bağlantısı", "Kamida 10 belgi yozing": "En az 10 karakter yazın",
  "Employer task yuborildi": "İşveren görevi gönderildi", "Kandidat topshirig'ini kutmoqda...": "Adayın çalışması bekleniyor...",
  "Baholash mezonlari": "Değerlendirme kriterleri",
  "Score qanday hisoblandi — shaffof formula": "Puan nasıl hesaplandı — şeffaf formül",
  "Practice topshiriqlar": "Pratik görevler", "Mentor feedback": "Mentor geri bildirimi", "Employer feedback": "İşveren geri bildirimi",
  "Ommaviy passport": "Herkese açık pasaport", "Ko'rinishni o'zgartirish": "Görünürlüğü değiştir", "Skill'larim": "Becerilerim",
  "Passport'ni ochish →": "Pasaportu aç →", "skill_empty": "Henüz beceri yok — değerlendirme yapın.", "Ko'rinish": "Görünürlük",
  "Employer AI Dashboard": "İşveren AI Paneli", "ai_d": "Huni, süre ve maliyet — canlı hesaplama. Telegram'da 300 CV değil, yalnızca kanıtlanmış pasaportlar.",
  "Kandidatlar bazasi": "Aday veritabanı", "Time-to-hire": "Time-to-hire", "6 kun": "6 gün", "cv_note": "CV elemesiyle 21 gündü",
  "Tejalgan xarajat": "Tasarruf", "1.8 mln": "1,8 mn", "fee_note": "som — ajans ücretleri olmadan", "Verified kandidat": "Doğrulanmış adaylar",
  "passport_filter": "pasaporta göre filtreli", "Hired (pilot)": "İşe alınan (pilot)", "contract_soon": "resmî sözleşme yolda",
  "Hiring voronkasi — Applied → Hired": "İşe alım hunisi — Applied → Hired", "Tezkor amallar": "Hızlı işlemler",
  "Yangi loyiha yaratish": "Yeni proje oluştur", "brief_skills": "brief + beceri gereksinimleri", "Blind review navbati": "Kör inceleme sırası",
  "ta anonim submission": "anonim çalışma", "Interview belgilash": "Mülakat planla", "kandidat_tanlang": "aday seçin",
  "Offer yuborish": "Teklif gönder", "task_passed": "görevi geçen adaylara",
  "Loyihalaringiz": "Projeleriniz", "Loyiha yaratish": "Proje oluştur", "Loyihalar yo'q": "Proje yok",
  "pr_empty_b": "İlk gerçek projenizi oluşturun — öğrenciler başvuracak.", "Admin tasdig'ida": "Yönetici onayında",
  "Loyiha yopildi": "Proje kapatıldı", "Yangi loyiha": "Yeni proje", "Sarlavha": "Başlık", "Tavsif": "Açıklama",
  "Kerakli skill'lar": "Gerekli beceriler", "Daraja": "Seviye", "Davomiylik (kun)": "Süre (gün)", "To'lov (so'm)": "Ödeme (som)",
  "O'rinlar soni": "Pozisyon sayısı", "Yaratish (admin tasdig'iga yuboriladi)": "Oluştur (onaya gönderilir)",
  "err_project": "Başlık (5+ karakter) ve en az 1 beceri seçin", "created_ok": "Proje oluşturuldu — yönetici onayından sonra yayınlanır",
  "Skill (verified)": "Beceri (doğrulanmış)", "Min readiness": "Min hazırlık", "ta kandidat topildi": "aday bulundu",
  "verified_only": "yalnızca doğrulanmış becerilere göre", "Passport'ni ko'rish": "Pasaportu gör",
  "empty_cand_t": "Filtrelere uyan aday yok", "empty_cand_b": "Filtreleri gevşetin veya minimum hazırlığı düşürün.",
  "Blind Review Panel": "Kör İnceleme Paneli", "blind_d": "Adil seçim: ad, üniversite ve fotoğraf gizli. Yalnızca kod ve sonuç puanlanır.",
  "Anonim submission": "Anonim çalışma", "shaxs yashirilgan": "kimlik gizli", "O'rtacha": "Ortalama", "Shaxs ochildi": "Kimlik açıklandı",
  "anonim": "anonim", "Bahoingiz": "Puanınız", "Bahoni yozish": "Puanı kaydet", "Shaxsni ochish": "Kimliği açıkla",
  "blind_tip": "İpucu: kimliği en az 2 puandan sonra açıklayın — adillik budur.",
  "reveal_t": "Kimliği açıklamadan önce puanlar kaydedilmiş olmalı — adillik garantisi budur.",
  "Hozir yozilgan baholar": "Kaydedilen puan", "Baribir ochish": "Yine de açıkla", "shaxs_ochildi_d": "Kimlik açıklandı — pasaporta gidin",
  "empty_blind_t": "Çalışma yok", "empty_blind_b": "Adaylar işveren görevini gönderince burada anonim görünür.",
  "Kamida 5 belgili izoh yozing": "En az 5 karakter yazın", "Baho yozildi — shaxs hali yashirin": "Puan kaydedildi — kimlik hâlâ gizli",
  "Interview'ga taklif": "Mülakata davet et", "Invite to Interview": "Mülakata davet et", "Interviewlar yo'q": "Mülakat yok",
  "int_empty_e": "Adayları mülakata davet edin — Meet/Zoom bağlantısı yeterli.", "Interview taklifi": "Mülakat daveti",
  "Taklif yuborish": "Davet gönder", "Interview taklifi yuborildi": "Mülakat daveti gönderildi", "Yakunlandi": "Tamamlandı",
  "Interview yakunlandi": "Mülakat tamamlandı", "Kandidatni tanlang": "Aday seçin",
  "Create Employer Task": "İşveren görevi oluştur", "Topshiriqlar yo'q": "Görev yok",
  "et_empty_b": "Mülakattan sonra adaylara küçük gerçek bir görev verin — sonucu burada değerlendirin.",
  "Yangi employer task": "Yeni işveren görevi", "Kandidat va sarlavha kiriting": "Aday ve başlık girin",
  "Submission baholash": "Çalışmayı değerlendir", "Feedback yozing": "Geri bildirim yazın", "Baho yuborildi": "Puan gönderildi", "Submission": "Submission",
  "Offerlar yo'q": "Teklif yok", "of_empty_b": "Görevi veya mülakatı geçen adaylara teklif gönderin.", "Pozitsiya": "Pozisyon",
  "Oylik": "Maaş", "Xabar": "Mesaj", "Interview/task o'tganlar ro'yxati": "Mülakat/görev geçenler listesi",
  "Avval interview yoki task o'tkazing": "Önce mülakat veya görev yapın", "Offer yuborildi!": "Teklif gönderildi!",
  "legal_employer": "İş sözleşmesini elektronik devlet sisteminde düzenleyin — platform yalnızca durumu izler.",
  "Kompaniya verifikatsiyasi kutilmoqda.": "Şirket doğrulaması bekleniyor.", "ver_note": "Projeleriniz, KASBORA yöneticisi hesabı onaylayınca yayınlanır.",
  "Mentor tekshiruv paneli": "Mentor inceleme paneli", "mentor_d": "5 kritere göre puan + yazılı geri bildirim — sonuç öğrencinin pasaportuna işlenir.",
  "Navbat bo'sh": "Sıra boş", "mentor_empty_b": "Öğrenciler görev gönderince burada görünür.",
  "Tekshirish va feedback": "İncele ve geri bildirim ver", "Feedback berish": "Geri bildirim ver", "Texnik sifat": "Teknik kalite",
  "Kommunikatsiya": "İletişim", "Muammoni yechish": "Problem çözme", "Deadline'ga rioya": "Teslim tarihine uyum",
  "Jamoa bilan ishlash": "Ekip çalışması", "Umumiy": "Genel", "PASSED bo'ladi": "PASSED olur", "FAILED bo'ladi": "FAILED olur",
  "fb_placeholder": "Güçlü yönler ve gelişim alanları...", "Feedback yuborish": "Geri bildirim gönder",
  "fb_ok": "Geri bildirim gönderildi — pasaporta eklendi", "Yakunlangan feedbacklar": "Tamamlanan geri bildirimler", "Hozircha feedback yo'q": "Henüz geri bildirim yok",
  "fb_empty_b": "Sıradaki görevleri inceleyin — sonuçlar burada kalır.",
  "Jami talabalar": "Toplam öğrenci", "Assessment yakunlagan": "Değerlendirmeyi tamamlayan", "Real loyiha qatnashchisi": "Gerçek proje katılımcıları",
  "Ishga joylashgan": "İşe yerleşen", "O'rtacha Work Readiness": "Ortalama Work Readiness", "Employment rate": "İstihdam oranı",
  "Import qilish": "İçe aktar", "import_ok": "2 öğrenci hesabı oluşturuldu", "edu_note": "EduOS/SIS API entegrasyonu yolda — şimdilik CSV.",
  "Skill bo'yicha o'rtacha ball": "Beceriye göre ortalama puan", "Employment voronkasi": "İstihdam hunisi",
  "North Star: Verified-to-Hired Rate": "North Star: Verified-to-Hired Rate",
  "north_star_d": "Doğrulanmış deneyimi olan kaç öğrenci işe girdi — girişimin gerçek değeri bu metrikte.",
  "uni_t": "TATU — Üniversite paneli", "uni_d": "Öğrenci hazırlığını gerçek zamanlı izleyin.",
  "Tasdiqlash kutilmoqda": "Onay bekleyenler", "admin_no_projects": "Bekleyen proje yok.", "E'lon qilingan": "Yayınlananlar",
  "Loyiha tasdiqlandi va e'lon qilindi": "Proje onaylandı ve yayınlandı", "Loyiha rad etildi": "Proje reddedildi",
  "Verifikatsiya kutilmoqda": "Doğrulama bekleyenler", "verifikatsiya qilindi": "doğrulandı", "BLOKLANGAN": "ENGELLİ",
  "Bloklash": "Engelle", "Blokdan chiqarish": "Engeli kaldır", "Bloklandi": "Engellendi", "Blokdan chiqarildi": "Engel kaldırıldı",
  "Skill tahrirlash": "Beceriyi düzenle", "Nomi": "Ad", "Skill saqlandi": "Beceri kaydedildi",
  "KASBORA ekotizimi": "KASBORA ekosistemi", "← Bosh sahifa": "← Ana sayfa", "eco_h": "Platform bir web sitesinden büyük",
  "eco_p": "Telegram Mini App, Open API ve ödeme/eğitim entegrasyonları KASBORA'yı tek yetenek altyapısına dönüştürür. Pilotta canlı olanlar şimdi çalışıyor, gerisi yol haritasında.",
  "PILOTDA JONLI": "PİLOTTA CANLI", "MOBIL": "MOBİL", "eco_tg_h": "Telegram Mini App — ilerleme cebinizde",
  "eco_tg_p": "Özbekistan'da Telegram ana kanal. Öğrenci değerlendirme sonuçlarını, mülakat davetlerini ve proje haberlerini bot üzerinden alır; Mini App içinde — hazırlık, görevler ve pasaport tek yerde.",
  "tg1_t": "Gerçek zamanlı bildirimler", "tg1_d": "mülakat, sonuç, geri bildirim — kontrol yerine push", "tg2_t": "Telegram'da değerlendirme", "tg2_d": "MCQ sorular bot içinde, süreli",
  "tg3_t": "iOS/Android uygulaması yolda", "tg3_d": "PWA zaten çalışıyor, native — Faz 2", "eco_bot": "pilot için açık · /start ile başlar",
  "API key": "API anahtarı", "Misol — passport verifikatsiya kodi": "Örnek — pasaport doğrulama kodu",
  "Integratsiyalar": "Entegrasyonlar", "int_d": "Pazara derin bağlantı", "JONLI": "CANLI", "YO'LDA": "YOLDA", "REJA": "PLAN", "PILOT": "PİLOT",
  "i_click": "Proje ödemeleri ve işveren tarifeleri — pilotta bağlı", "i_tg": "Bildirim, değerlendirme ve Mini App kanalı",
  "i_eduos": "Üniversite LMS ile öğrenci senkronizasyonu (şimdilik CSV)", "i_hris": "İşe alınan adayların 1C:ZUP ve diğer HR sistemlerine aktarımı",
  "i_gov": "Elektronik iş sözleşmesi — hukuki inceleme aşaması", "i_api": "Pasaport, aday ve readiness uç noktaları",
  "i_mail": "Değerlendirme, teklif ve geri bildirim mesajları", "i_push": "Mobil uygulamayla birlikte, Faz 2",
  "Roadmap": "Yol haritası", "rm_d": "Ne zaman ne gelir", "rm1_p": "FAZ 1 · Şimdi", "rm1_t": "MVP — kanıtla", "rm2_p": "FAZ 2 · 3–6 ay",
  "rm2_t": "Genişleme", "rm3_p": "FAZ 3 · 6–12 ay", "rm3_t": "Altyapı",
  "rm1_1": "Kimlik doğrulama + 5 rol paneli", "rm1_2": "Değerlendirme motoru (anti-cheat)", "rm1_3": "Gerçek projeler + Kör inceleme", "rm1_4": "Beceri Pasaportu + QR", "rm1_5": "Telegram bot (pilot)",
  "rm2_1": "Native mobil uygulama", "rm2_2": "EduOS/SIS API entegrasyonu", "rm2_3": "AI geri bildirim üreteci", "rm2_4": "Tam Click/Payme akışı", "rm2_5": "Yeni meslekler (QA, Design)",
  "rm3_1": "Üniversite SaaS", "rm3_2": "Dijital sertifikalar", "rm3_3": "my.gov.uz araştırması", "rm3_4": "API pazaryeri", "rm3_5": "Bölgesel genişleme",
  "Demo kirish →": "Demo giriş →", "demo_login_d": "Demo hesaplarla 5 rolü de deneyin — parola:", "Bosh sahifa": "Ana sayfa",
  "Bugungi progress": "Bugünkü ilerleme", "Keyingi assessment →": "Sonraki değerlendirme →", "wr_phone": "İşe hazır · bu hafta +6",
  "Loyiha": "Proje", "review'da": "incelemede",
  "proc_p": "KASBORA'da öğrenci sadece kayıt olmaz — tüm zincirden geçer: değerlendirmelerle kanıtlanan bilgi, mentor incelemeleri, gerçek şirket projelerinde çalışma ve tüm sonuçlar Beceri Pasaportu'nda toplanır. İşveren özgeçmiş değil, kanıt görür.",
  "proc_lifecycle": "Aday yaşam döngüsü — işe alım hunisi",
  "proc_lifecycle_d": "Her başvuru bu zincir boyunca ilerler. Öğrenci durumunu gerçek zamanlı görür; işveren her aşamada yalnızca kanıtlanmış sonuçlarla çalışır.",
  "proc_reject": "Herhangi bir aşamada reddedilirse",
  "sk_sources_h": "6 kanıt kaynağı", "isbot_emas": "kanıt değil", "sk_levels_h": "Beceri seviyeleri",
  "sk_levels_d": "Seviye, değerlendirme puanına göre otomatik verilir ve her yeni kanıtla güncellenir — pasaport her zaman en güçlü kaynağı gösterir.",
  "pp_bands_h": "Work Readiness ölçeği",
  "pp_b1": "Yolun başında — ilk değerlendirme bekliyor.",
  "pp_b2": "Beceriler oluşuyor — pratik görevler gerekli.",
  "pp_b3": "İşverenler görüyor: mülakata hazır aday.",
  "pp_b4": "Yüksek talep — gerçek proje deneyimiyle.",
  "faq_contact": "Başka sorunuz mu var?",
  "faq_contact_d": "Pilot ekip iş günlerinde 2 saat içinde yanıtlar. Telegram botu üzerinden de yazabilirsiniz.",
  "full_read": "Tam bölümü aç",
  "idx_h": "Derinlemesine keşfedin",
  "idx_t": "KASBORA'yı daha yakından tanıyın",
  "idx_p": "Süreç, beceriler, Beceri Pasaportu ve SSS — her biri kendi tam sayfasında. İlginizi çekeni açın.",
  "idx_proc_d": "Bilgiden işe — 6 adımlık tam yolculuk ve aday hunisi nasıl çalışır.",
  "idx_sk_d": "Pilottaki 8 beceri, kanıt kaynakları ve seviyeleri.",
  "idx_pp_d": "En önemli belge — QR doğrulama, anti-cheat ve şeffaf hazırlık formülü.",
  "idx_faq_d": "En çok sorulan sorular ve net yanıtlar.",
  "6 bosqich": "6 adım", "8 skill": "8 beceri", "QR + PDF": "QR + PDF", "6 savol": "6 soru",
};
